### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by blogclub** [aleganza/akuse#1]
Hello, how does the project work and there is an error? Can you tell me how to solve it?
![截屏2023-09-02 11 52 28](https://github.com/aleganza/akuse/assets/72648772/a3fa9a0d-d6cc-4daa-8287-82b332aee266)

**Comment by aleganza** [comment]
Hi, that's the file where the anilist api things are, it's not public yet so it won't work unless for me. Today I will work on that part so everyone can clone it without problems.

**Comment by blogclub** [comment]
> Hi, that's the file where the anilist api things are, it's not public yet so it won't work unless for me. Today I will work on that part so everyone can clone it without problems.

thanks!

**Comment by aleganza** [comment]
Hi, does it work now?

**Comment by blogclub** [comment]
> Hi, does it work now?

Yes, it does. Thank you very much. But your readme file "cliendData.js" should be "clientData.js", you maybe wrote it wrong.

**Comment by aleganza** [comment]
Fixed it! Thank's for noticing.
