### ISSUE TITLE
No Anilist or any login in app

### ISSUE THREAD

**Issue by ghost** [aleganza/akuse#111]
Is this a new update cuz i dont see any button to login?

**Comment by aleganza** [comment]
send a pic of your navbar

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/65936120-fae4-4265-823e-b5995a66f18e)

**Comment by aleganza** [comment]
press the rightmost button

**Comment by ghost** [comment]
> press the rightmost button

aah ssorry my bad! i thought it was the exit button or smth. it looks like that uk? thanks

**Comment by aleganza** [comment]
yea a friend of mine already told me that😂
