### ISSUE TITLE
The episodes of Tensura are Incorrect

### ISSUE THREAD

**Issue by ghost** [aleganza/akuse#112]
For eg: when i click of episode 16 it plays episode 15 but the title is of episode 16. same happens for a couple of other episodes for the same anime.

**Comment by ghost** [comment]
Yeah it still remains the same even after a new episode is released. Even after episode 16 is released it plays episode 15 on the title of 16th episode

**Comment by aleganza** [comment]
probably related to #96 :(
will fix soon I hope
