### ISSUE TITLE
Can no longer view any content while signed in to Anilist account

### ISSUE THREAD

**Issue by CUD** [aleganza/akuse#115]
I started seeing this when I opened Akuse today.

![image](https://github.com/user-attachments/assets/1f4df754-f493-4d56-913f-d922a4d804e8)

After logging out of Anilist it looks as normal and I can watch videos fine too.

![image](https://github.com/user-attachments/assets/df2fcfe6-ce19-479e-b43d-7c75e77248ed)

I assume something is wrong with the API at the moment?
I also tried revoking the app in Anilist and authorising again but no difference.

Maybe unrelated but this Windows 11 updated installed today KB5040527.
Akuse was working fine yesterday prior to this update so thought I'd mention in case it isn't the API itself.

**Comment by aleganza** [comment]
yep it must be something related to its api, we just have to wait for a fix

**Comment by CUD** [comment]
Closing as this looks to be resolved now
