### ISSUE TITLE
App Availability 

### ISSUE THREAD

**Issue by ParsonsPT** [aleganza/akuse#118]
Hello akuse can you please make your app available for Android(samsung galaxy a03 core),my phone.

**Comment by TwinAwakenings** [comment]
Don't think its planned but you can use this for now https://github.com/aniyomiorg/aniyomi/releases/tag/v0.16.4.3
Extensions repo (Open this on the phone while having aniyomi installed): aniyomi://add-repo?url=https://raw.githubusercontent.com/almightyhak/aniyomi-anime-repo/main/index.min.json
As for extensions I recommend Gogoanime and HiAnime

**Comment by aleganza** [comment]
hi mate appreciate your greetings but this app will not be ported for mobile, I may suggest you a very cool one that I also use: https://github.com/kodjodevf/mangayomi
