### ISSUE TITLE
Source not found.

### ISSUE THREAD

**Issue by AzureCerulean** [aleganza/akuse#122]
Error: Source not found.

This is happening with multiple anime.

ex. "The Ossan Newbie Adventurer, Trained to Death by the Most Powerful Party, Became Invincible"

**Comment by aleganza** [comment]
could you list them?

**Comment by Nansess** [comment]
> could you list them?

tends to happen with any ummm all "explicit ones" lol, should prob have a check of some sort to not include these

**Comment by aleganza** [comment]
thought it was due to the new version and new matching system but if this issue only regards the _explicit ones_, it's normal.

**Comment by aleganza** [comment]
any news?

**Comment by AzureCerulean** [comment]
ex. "The Ossan Newbie Adventurer, Trained to Death by the Most Powerful Party, Became Invincible"

**Comment by aleganza** [comment]
it's working for me. guess it's something about vpns
