### ISSUE TITLE
[Feature Request] Source selection option

### ISSUE THREAD

**Issue by Shubu8974** [aleganza/akuse#123]
Hi, could you please add an option to manually select the server for anime sources?

I’d also like to request the addition of these new sources: Anix.vc, animesuge.to, and animepahe.
cuz i'm getting low sound quality problem on gogoanime and other sources.

**Comment by aleganza** [comment]
the english server will remain only one, I noticed some bad audio from gogoanime too, maybe I'll swap it with a better provider one day.
