### ISSUE TITLE
Discord RPC 

### ISSUE THREAD

**Issue by Fanatic9** [aleganza/akuse#124]
is it possible to make it so the timer doesn't keep going when you pause an episode ? 
i already like the fast progress akuse has gotten so far but i was wondering if that was something that overlooked or in progress

**Comment by aleganza** [comment]
since I didn't make the discord rpc myself I didn't know about this.
will look into it!

**Comment by Fanatic9** [comment]
Thanks a lot !

**Comment by Fanatic9** [comment]
i wanted to add , is it possible for the RPC to show the season and episode playing with what i said above added ? currently the rpc only tracks the software as being open not the episodes of animes which is why the counter keeps going. 
If it helps when i was using jellyfin i was using a plugin that pretty much linked everything i watched ( movies/shows/anime) and it showed season, episodes and also stopped when i paused . https://github.com/Radiicall/jellyfin-rpc , i'm not saying to copy this exactly but if it can help achieve a closer outcome it would be nice . and thanks again for the updates !

**Comment by LeinadUchiha** [comment]
there is no way to disable it?

**Comment by aleganza** [comment]
you can disable the rpc directly from discord atm
