### ISSUE TITLE
Feature Request: Allow selecting or de-selecting providers.

### ISSUE THREAD

**Issue by KoxSosen** [aleganza/akuse#127]
Currently there is no way in the app to manually change the providers used to stream media. My feature request would be to add a way for users to change which providers they would like to use. This is a very niche feature, but would be a welcomed one. And, thank you for creating this amazing app!

**Comment by aleganza** [comment]
The whole point is that the user doesn’t need to worry about which provider to use; they just pick their language and they're good to go.
