### ISSUE TITLE
Next Episode Release Date Not Displayed, App Stuck on 'Resume from Ep. X' for Ongoing Series

### ISSUE THREAD

**Issue by TetraSsky** [aleganza/akuse#137]
Description : I was watching The Elusive Samurai and recently finished episode 9. However, instead of showing the date for the next episode, the app still shows "Resume from Ep. 9." This only affects the newest releases (That are still/currently publishing) where it should be showing a date. I've tested with many others, and it does the same thing.

How to reproduce : Search for an anime still releasing episodes, go to the latest entry, and skip to the end. Akuse will show "Resume from Ep. X" instead of the normal next release date like it used to.

OS : Windows 11

Screenshots :
(Screenshot1 - How it should be) ![image](https://github.com/user-attachments/assets/61ed47f3-a8ec-4a67-929f-63fc97504d13)
(Screenshot 2 - How it shows now) ![image](https://github.com/user-attachments/assets/f41a5582-9ccb-4baf-8627-d954b715dcd3)

**Comment by ch0nker** [comment]
If you don't want to wait for the next update, I've built it on my fork [here](https://github.com/ch0nker/akuse/releases/tag/1.6.3).
