### ISSUE TITLE
Dragon Ball stream source query

### ISSUE THREAD

**Issue by CUD** [aleganza/akuse#141]
**Describe the bug**
Up until episode 68 the quality was available in 1080p but from ep69 it seems to be 480p max.

As I'm not quite sure what sources this is using, I was wondering if there is a way to ensure this defaults to the same source that it used originally? Assuming this source has these remaining eps..

**Comment by aleganza** [comment]
I guess that it's just the source that provides those qualities as they are.
If you tell me which Anime it is I can check.

**Comment by CUD** [comment]
> I guess that it's just the source that provides those qualities as they are. If you tell me which Anime it is I can check.

The anime is Dragon Ball
From ep69 is when the only quality options it shows are 480p

![image](https://github.com/user-attachments/assets/cb2dd889-9dc0-4df4-a981-49f553a4e115)

**Comment by aleganza** [comment]
oh alright I thought you was general when you said dragonball in the title.

**Comment by CUD** [comment]
> oh alright I thought you was general when you said dragonball in the title.

All good, maybe I should have specified OG Dragon Ball

**Comment by aleganza** [comment]
> I guess that it's just the source that provides those qualities as they are. If you tell me which Anime it is I can check.

^^^
