### ISSUE TITLE
Quality selection does not work

### ISSUE THREAD

**Issue by SultuDhadel** [aleganza/akuse#146]
When I try to change the quality from the settings in the player it simply does nothing. The menu drops does but it does not do anything when I click on any option.

 - OS: Windows 
 - Version: akuse-beta 1.6.0

**Comment by that-weird-dude** [comment]
Bro, me too. And I can't watch 1080p anime with my poor wifi

**Comment by SultuDhadel** [comment]
Same


> Bro, me too. And I can't watch 1080p anime with my poor wifi
