### ISSUE TITLE
The player episodes list sucks!

### ISSUE THREAD

**Issue by SultuDhadel** [aleganza/akuse#153]
**Describe the bug**
The episodes list in the player does not play the episode when clicked on. You have to double-click and then wait until it decides to play it. The list also disappears after 3 seconds, giving you no time to browse the episodes.

**To Reproduce**
Just try to use the episodes option in the player

**Expected behavior**
- [x] The episodes should be loaded instantly
- [x] The list should stay visible until the user close it 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Akuse Version: 1.6.0

**Comment by aleganza** [comment]
fax

**Comment by aleganza** [comment]
half fixed in 1.7.0
