### ISSUE TITLE
Please add button to remove hentai

### ISSUE THREAD

**Issue by Sobble2546** [aleganza/akuse#159]
**Is your feature request related to a problem? Please describe.**
I cant stand having hentai all over my feed

**Describe the solution you'd like**
Just make a button to remove hentai from the feed

**Describe alternatives you've considered**
Or make it that hentai only comes when u search it up or
Have a option to only show the anime that ur watching

**Additional context**
im flabbergasted

**Comment by aleganza** [comment]
how in the world you have hentai all over your feed😔

**Comment by ch0nker** [comment]
If you're getting it on anything other than the "Recently Aired" anime, go to https://anilist.co/settings/media then disable "18+ Content".

**Comment by ghost** [comment]
you are getting hentai on your feed because the code does not sort out 18+ content I believe.
