### ISSUE TITLE
Bleach early episodes missing

### ISSUE THREAD

**Issue by GDKekkles** [aleganza/akuse#160]
The entire beginning of Bleach is completely wrong, its missing 2-4 episodes of content, including the most integral one where it shows Ichigo receiving his temporary shinigami powers, and skips 2-4 episodes ahead to where he's already killing hollows. The quality is also abysmally bad compared to almost every streaming site (no hate, just sayin'); consider the comparison between 1080p and 480p.

Warm regards,

A based Bleach enjoyer

**Comment by darkhappy** [comment]
Seems that it's pulling the OVA rather than the actual anime, which only has 2 episodes

https://anitaku.pe/category/bleach-ova
