### ISSUE TITLE
Can't go to a specific Episode. Moreover App is not working for One Piece

### ISSUE THREAD

**Issue by ayyadevaraakash** [aleganza/akuse#172]
I wanted to watch One Piece episode 1122. I tried many ways but was not able to figure out how to reach to episode 1122. In the player we have a button to show episodes but it does not work for "One Piece" anime.

Moreover One Piece episodes show ?/?
How to reach to a specific episode. I think you should add a button so that we can go to a specific episode when the number of episodes are large.

**Comment by aleganza** [comment]
in 1.9.0 will be fixed
