### ISSUE TITLE
Fillers not showing

### ISSUE THREAD

**Issue by ayyadevaraakash** [aleganza/akuse#173]
Filler episodes should be marked with some other color or there should be some indication to show that it's a filler episode.

Moreover, you can add a feature like-- a button that says "Without Fillers" and the list will be filtered with only CANON episodes.

Anyways this feature will take time but for time being just give some indication that the episode is a filler or CANON.

**Comment by toralol** [comment]
https://github.com/akuse-app/akuse/issues/152
