### ISSUE TITLE
one piece

### ISSUE THREAD

**Issue by Dieexekill** [aleganza/akuse#175]
**Describe the bug**
it said that the number of episodes is ?/?

**To Reproduce**
unclear it only happened on my monter /pc

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Dieexekill** [comment]
sorry for shuch litle info

**Comment by Dieexekill** [comment]
and

**Comment by Dieexekill** [comment]
thank

**Comment by Dieexekill** [comment]
you

**Comment by Dieexekill** [comment]
very

**Comment by Dieexekill** [comment]
much

**Comment by aleganza** [comment]
#172
