### ISSUE TITLE
Mr Osomatsu season 3 doesen't work

### ISSUE THREAD

**Issue by RacheleBurgio** [aleganza/akuse#181]
**Describe the bug**
it appears a "source not found" on top of the player when I start the anime

**To Reproduce**
I just open the episode and that happens

**Expected behavior**
it should start the episode i guess?

**Screenshots**
![Immagine 2024-11-07 113954](https://github.com/user-attachments/assets/27f8ee19-88b7-4f31-8cf4-1597140fd4eb)

**Desktop (please complete the following information):**
 - windows 10

**Additional context**

**Comment by aleganza** [comment]
the anime doesn't exist on AnimeUnity 😞
