### ISSUE TITLE
blank screen/ nothing showing 

### ISSUE THREAD

**Issue by Fanatic9** [aleganza/akuse#183]
**Describe the bug**
first time ever since using this app where i get a blank screen where nothing is showing, tried logging in and out and nothing

**To Reproduce**
?

**Expected behavior**
for animes to show

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  windows 11 24h2
![akuse_0nKFsX1crA](https://github.com/user-attachments/assets/729296d4-6867-42cb-b7d7-9cdbd19062a3)
![akuse_VxjuxiQmMy](https://github.com/user-attachments/assets/80d1f898-e7c8-4fcf-a229-e8a9d48d3b47)

**Additional context**

**Comment by AlphaScratch** [comment]
Same issue here, first install as well.
Edit: Attempted to uninstall and install 1.8.0 to test, then ignore update prompt, however problem persists and nothing loads. (This is a windows install as well)

**Comment by Achyut1-cyber** [comment]
same issue please solve this

**Comment by Achyut1-cyber** [comment]
![Screenshot (19)](https://github.com/user-attachments/assets/4a0b0af1-ec06-4699-9130-bf2b2760bd89)

**Comment by aleganza** [comment]
I'll give a look later 🥰

**Comment by gwshdude** [comment]
In case this helps solve the issue, I also have the issue, and initially logging out fixed the issue. However, I wanted to be logged in so my progress would be kept track of on anilist so I reinstalled akuse, even trying different versions but the issue persists on all versions regardless of being logged in or not now.

**Comment by ceyaima** [comment]
i'm assuming akuse uses the anilist api to obtain the anime catalogue and since the anilist api is currently down, i'm also assuming that's why it's not working.

for updates regarding the api, you can join the anilist discord

**Comment by Fanatic9** [comment]
> i'm assuming akuse uses the anilist api to obtain the anime catalogue and since the anilist api is currently down, i'm also assuming that's why it's not working.
> 
> for updates regarding the api, you can join the anilist discord

that seems to be likely, i opened the app today and everything works as normal

**Comment by Achyut1-cyber** [comment]
wow problem solve thanks!
