### ISSUE TITLE
Showing nothing

### ISSUE THREAD

**Issue by SayKahlil** [aleganza/akuse#187]
When i first downloaded this app i was able to watch anime, But now every time i load in its shows absolutely nothing just blank.
![Screenshot 2024-11-15 024220](https://github.com/user-attachments/assets/a30f94c2-7b07-4f50-9fca-c743e8b396fa)

**Comment by aleganza** [comment]
#184

**Comment by SayKahlil** [comment]
> #184

Ohh alr thank you
