### ISSUE TITLE
cant instal properly on arch linux

### ISSUE THREAD

**Issue by vansh9131r** [aleganza/akuse#189]
Hello, i have been trying to install the akuse-git package from the AUR link : https://aur.archlinux.org/packages/akuse-git

**To Reproduce**
yay -S akuse-git
**Expected behavior**
to install akuse

**Screenshots**
![image](https://github.com/user-attachments/assets/d45b30b2-6c50-42c8-89d6-8630972371b5)

**Desktop (please complete the following information):**
 endeavour os

**Additional context**
N.A

**Comment by aleganza** [comment]
sorry but someone else created that arch linux support back then, don't know how to help
