### ISSUE TITLE
List issues

### ISSUE THREAD

**Issue by Madagarian** [aleganza/Akuse#4]
Added several shows to my lists and the lists did not update until after I relaunched the program.

Progress and score are mandatory in thelist editor; I can't add a show to anything
(planning or otherwise) without scoring something I'm not watching/haven't
finished. And same for progress, either remove mandatory field flag or add a default starting episode of 1.

Additionally, since these fields are mandatory, I'm required to manually select the episode number when listing a completed show. Please make it auto-populate the latest episode number.

**Comment by aleganza** [comment]
Issue 1) Yep I know 😅 I still have to fix that thing.
Issue 2) If that's annoying I will certainly fix it. About the last two rows, I hadn't even though about this feature. I will implement it.
