### ISSUE TITLE
[FEATURE] Add SIMKL Watchlist Sync integration

### ISSUE THREAD

**Issue by Azmarine13** [aleganza/akuse#81]
Would be great, if you added a SIMKL watchlist sync integration with login option 👍 

**Here are few links, that might help:**

- Anime Section: https://simkl.com/anime/
- Anime API: https://simkl.docs.apiary.io/#reference/anime
- API Documentation: https://api.simkl.com/
- Sync API: https://simkl.docs.apiary.io/#reference/sync

**Comment by aleganza** [comment]
someone already asked for other login options, like mal or kitsu, but atm I'll only keep anilist
