### ISSUE TITLE
Pictures and Episodes not showing when clicked on 

### ISSUE THREAD

**Issue by Fanatic9** [aleganza/akuse#86]
gotta say as a jellyfin user and former taiga user , this app has a bright future and is going in the right direction.
with that said it still has a long way to go but it's still in beta so it's not surprising but i just wanted to share an "issue" i encountered so far : 
when clicking on any show , background and episodes pictures just don't show up.
they do work when you click on them but you can't really see which episode you're clicking, i also wanted to talk about discord integration.
i know someone has already opened an issue about it showing what you're currently watching but i'd like to add it would also be cool if on top of that we could see ( the season,episode, the episode time counter ) and also if it's possible to add an anilist link button to whichever episode you're currently watching but that's just extra.
anywho thanks a lot in advance for this app and all the work you guys are doing !
![akuse_j2Fd1hMi6g](https://github.com/akuse-app/akuse/assets/167824035/90fd3bb6-96bc-49eb-b4d4-fb43994f86ab)
![BAZa0KJuAI](https://github.com/akuse-app/akuse/assets/167824035/b571ed4e-320e-447a-b6da-0e0af7534b54)

**Comment by aleganza** [comment]
try reloading the app (or waita bit), that may be a temporarily issue due to your connection.

**Comment by Fanatic9** [comment]
i can confirm that this was my bad , had adguard home on and it blocked the api from fetching pictures and other details.
thanks for the quick response and keep up the good work
