### ISSUE TITLE
[Feature] English subs in dubbed streams

### ISSUE THREAD

**Issue by JuanPardos** [aleganza/akuse#89]
This is a bit of feature mixed with QOL but as a non native english speaker I would find helpful the ability to use subs (english) in dubbed streams. As soon as I activate the dub option the subtitles disappear, at least in every show I tried.
I mean, they could even be the same english subtitles of non-dubbed, I don't mind.
Don't know if this is doable because I suppose the subtitles come embedded in the stream and you just show/hide it and dubbed stream is a completely different source but...

Thanks in advance, the app looks nice.

**Comment by Sukarett2** [comment]
While the subtitles are baked into the stream, I believe it is possible for both sub and dub to be loaded for an episode. In this case, the subbed video plays while the dubbed audio is actually heard.

**Comment by aleganza** [comment]
eng sub and dub episodes come from two different url sources, so the only way to do it would be playing the 2 urls at the same time, showing only the subbed and hearing only the dubbed. it is something quite weird to add.

I would suggest to watch in eng subbed as japanese dubbing is much better to hear.

**Comment by aleganza** [comment]
closing as it will not be added :(
