### ISSUE TITLE
Toggle Discord Rich Presence

### ISSUE THREAD

**Issue by 0x96EA** [aleganza/akuse#92]
Before I make a PR for this I wanted to check if this was a wanted feature. I want to make a setting to toggle discord rich presence on or off. Thoughts?

**Comment by crashniels** [comment]
Sounds good. "Watch anime without ads" and the "Download App" button should also be toggleable.

**Comment by aleganza** [comment]
Discord rich presence is already "toggable" in discord, you can disable it from there, so it will not be toggable in the app.
