### ISSUE TITLE
Error in Running locally for development

### ISSUE THREAD

**Issue by blogclub** [aleganza/akuse#94]
[electronmon] waiting for a change to restart it
ERROR in main
Module not found: Error: Can't resolve '/Users/design/Downloads/akuse/src/main/preload.ts' in '/Users/design/Downloads/akuse',

There is no src/main/preload.ts file

**Comment by aleganza** [comment]
what command did you use?

**Comment by blogclub** [comment]
npm install, then npm start

**Comment by aleganza** [comment]
npm start should work anyway even if you get that error. try doing the command and wait for it to finish

**Comment by blogclub** [comment]
![截屏2024-06-18 21 39 43](https://github.com/akuse-app/akuse/assets/72648772/546d6a78-7914-4394-aaec-fba272599c12)

Is it right?

**Comment by aleganza** [comment]
yea.. it's the one from the readme file

**Comment by blogclub** [comment]
thanks
