### ISSUE TITLE
Wrong episodes playing

### ISSUE THREAD

**Issue by Fanatic9** [aleganza/akuse#96]
i really wanted to this to work out and use it instead of jellyfin but i think akuse has a problem with episodes that newly come out , i'm currently watching the newest season of reincarnated as a slime and whenever i play the "newest" episode, it plays the previous one instead even tho it has the title and number of the newest episode. 
![mpc-hc64_QsJk5gs5Pk](https://github.com/akuse-app/akuse/assets/167824035/0aac1ee8-b214-4b21-8127-91bd888f60d0)
![akuse_wGCHRcU8Uu](https://github.com/akuse-app/akuse/assets/167824035/b7d500b9-e512-4adf-885d-50ade7d87b5f)
![akuse_39ucpK0TCZ](https://github.com/akuse-app/akuse/assets/167824035/e45983bb-9137-435a-b41b-5578a3cbcba6)
i downloaded episode 11 of season 3 ( which is 59 counting all episodes of all seasons ), and it is the same episode as what's marked as episode 12 in akuse

**Comment by Fanatic9** [comment]
to be clear , everything looks and works right ( episode title , season and epi number and even the syncing with anilist works when finishing the episode ) but the actual episode that plays isn't the correct one

**Comment by aleganza** [comment]
![immagine](https://github.com/akuse-app/akuse/assets/73157384/8c6d21a4-f8e2-4ba9-8e20-8c25b7032723)

this issue is related to anime with atypical episode numbers, like this anime (has episode 0) or solo leveling (episode 7.5).
it still has to be fixed as atm I don't have much time to work on akuse, but you can still watch your favorite anime which do not have these atypical episodes!

**Comment by Fanatic9** [comment]
> ![immagine](https://private-user-images.githubusercontent.com/73157384/341895129-8c6d21a4-f8e2-4ba9-8e20-8c25b7032723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMDY1MDgsIm5iZiI6MTcxOTAwNjIwOCwicGF0aCI6Ii83MzE1NzM4NC8zNDE4OTUxMjktOGM2ZDIxYTQtZjhlMi00YmE5LThlMjAtOGMyNWI3MDMyNzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDIxNDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjdmZjI5ZDliYmM1YzJlMzEyOWY3MmRlNzBmNmVjNGUzYzg2M2IwMjlhZGQyNTkyN2ZlMjRjMjIxYjgzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-3RlRImChXsievfTUSk27ElOGlgElAu3WeCwJghJ64)
> 
> this issue is related to anime with atypical episode numbers, like this anime (has episode 0) or solo leveling (episode 7.5). it still has to be fixed as atm I don't have much time to work on akuse, but you can still watch your favorite anime which do not have these atypical episodes!

i see makes sense , thanks for the reply
